Chore(ci): Add integration test

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -33,6 +33,18 @@ jobs:
         uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
         with:
           prefix-key: "cargo"
-      - name: Run tests
-        run: cargo test --all --all-features --verbose
+      - name: Run unit tests
+        run: cargo test --lib --all-features --verbose
+        shell: bash
+      - name: Run integration test
+        run: |
+          exe=$(cargo test --test integration --no-run --message-format json \
+            | jq -r 'select(.reason == "compiler-artifact" and .executable? != null) | .executable')
+
+          if [ -z "$exe" ]; then
+            echo "executable not found"
+            exit 1
+          fi
+
+          sudo "$exe"
         shell: bash
